import { join } from 'node:path';
import { preprocess } from '../src/engine/image/preprocessor';
import { detectGrid } from '../src/engine/image/tableDetector';
import { prepareCellLines } from '../src/engine/pipeline';
import { recognizeShortLabel } from '../src/engine/ocr/glyphClassifier';
import { loadRaster, FIXTURES, ROOT, savePng } from '../tests/helpers/node';
const [name, r, c] = process.argv.slice(2);
const pre = preprocess(loadRaster(join(FIXTURES, name)));
const det = detectGrid(pre.binary);
const cell = det.grid!.cells.find((x) => x.row === Number(r) && x.col === Number(c))!;
console.log('cell', JSON.stringify(cell));
const dim = Math.max(pre.gray.width, pre.gray.height);
const inset = Math.max(3, Math.round(dim * 0.004));
let ink = 0;
for (let y = cell.y + inset; y < cell.y + cell.h - inset; y++) for (let x = cell.x + inset; x < cell.x + cell.w - inset; x++) ink += det.textInk.data[Math.round(y) * det.textInk.width + Math.round(x)];
console.log('ink', ink, 'area', (cell.w - 2 * inset) * (cell.h - 2 * inset));
const lines = prepareCellLines(pre.gray, det.textInk, cell, inset);
console.log('lines', lines.length);
lines.forEach((l, i) => { savePng(join(ROOT, 'tests/output', `cell-${r}-${c}-${i}.png`), l.image); console.log(i, 'inkHeight', l.inkHeight, JSON.stringify(recognizeShortLabel(l.image, 5))); });
